"""add like model

Revision ID: 85f43154cac7
Revises: c584ef41dabe
Create Date: 2023-07-18 19:05:27.350844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f43154cac7'
down_revision = 'c584ef41dabe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
